version: '3.1'

services:
  mysql_db:
    image: mysql
    restart: always
    container_name: 'mysql_db'
    ports:
      - 3306:3306
    volumes:
      - ./data_volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: p4sw00Rd